all:
		gcc server.c -o emailserver 
		gcc client.c -o emailclient
		echo Run ./emailserver port_num and ./emailclient ip_addr port_num on different terminals
clean:
		rm emailserver
		rm emailclient

cleane:
		rm emailserver
		rm emailclient
		rm *.txt
