all:
		@g++ -std=c++14 a2.cpp -o cw 
		@echo Run ./cw -i Ki -m Km -n Kn -f Kf -s Ps -T T -o outfile
		@echo Run python3 visualise.py outfile to plot results
clean:
		@rm cw

cleane:
		@rm cw
		@rm *.png
		@rm *.txt
